//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSender_MVVM_And_Entity_.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAdresses
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }

        public override string ToString()
        {
            if (Email != null) return Email;
            else return "";
        }
    }
}
